### ISSUE TITLE
Error : Class 'CRM_Rip_Upgrader_Base' not found 

### ISSUE THREAD

**Issue by lshaw1968** [eileenmcnaughton/org.wikimedia.rip#2]
Error : Class 'CRM_Rip_Upgrader_Base' not found dans require_once() (/var/www/clients/client1/web1/web/sites/default/files/civicrm/ext/org.wikimedia.rip/org.wikimedia.rip/CRM/Rip/Upgrader.php ligne 6)
#0 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Core/ClassLoader.php(165): require_once()
#1 [internal function]: CRM_Core_ClassLoader->loadClass()
#2 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Extension/Mapper.php(588): spl_autoload_call()
#3 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Extension/Upgrades.php(111): CRM_Extension_Mapper->getUpgrader()
#4 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Extension/Upgrades.php(42): CRM_Extension_Upgrades::getActiveUpgraders()
#5 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Admin/Page/Extensions.php(124): CRM_Extension_Upgrades::hasPending()
#6 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Core/Page/Basic.php(144): CRM_Admin_Page_Extensions->browse()
#7 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Admin/Page/Extensions.php(105): CRM_Core_Page_Basic->run()
#8 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(319): CRM_Admin_Page_Extensions->run()
#9 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem()
#10 /var/www/clients/client1/web1/web/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke()
#11 /var/www/clients/client1/web1/web/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke()
#12 /var/www/clients/client1/web1/web/modules/contrib/civicrm/src/Controller/CivicrmController.php(80): Drupal\civicrm\Civicrm->invoke()
#13 [internal function]: Drupal\civicrm\Controller\CivicrmController->main()
#14 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#15 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#16 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#17 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#18 /var/www/clients/client1/web1/web/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#19 /var/www/clients/client1/web1/web/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#20 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#21 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#22 /var/www/clients/client1/web1/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#23 /var/www/clients/client1/web1/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#24 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#25 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#26 /var/www/clients/client1/web1/web/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#27 /var/www/clients/client1/web1/web/core/lib/Drupal/Core/DrupalKernel.php(713): Stack\StackedHttpKernel->handle()
#28 /var/www/clients/client1/web1/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#29 {main}

**Comment by eileenmcnaughton** [comment]
That line seems to be gone in the 1.1 release https://github.com/eileenmcnaughton/org.wikimedia.rip/commit/76b9432ae87d54941011f5aa8900c2ee2b277c6d
